=== vbarab/webApp/src/main/java/com/epam/vb/entity/Blog/task_Schema/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://myFlowerSchema.kz"
           elementFormDefault="qualified">
    <element name="Flower">
        <complexType>
            <sequence>
                <element name="Name" type="string"/>

                <element name="Soil">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Sand"/>
                            <enumeration value="Silt"/>
                            <enumeration value="Clay"/>
                        </restriction>
                    </simpleType>
                </element>

                <element name="Origin" type="string"/>

                <element name="VisualParameters">
                    <complexType>
                        <sequence>
                            <element name="StemColor" type="string"/>
                            <element name="LeafColor" type="string"/>
                            <element name="AvarageSize" type="string"/>
                        </sequence>
                    </complexType>
                </element>

                <element name="GrowingTips">
                    <complexType>
                        <sequence>
                            <element name="Temperature" type="decimal"/>
                            <element name="Light">
                                <simpleType>
                                    <restriction>
                                        <enumeration value="Low"/>
                                        <enumeration value="Medium"/>
                                        <enumeration value="Hight"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="Watering" type="decimal"/>
                        </sequence>
                    </complexType>
                </element>

                <element name="Multiplying">
                    <simpleType>
                        <restriction>
                            <enumeration value="Seed"/>
                            <enumeration value="Leaf"/>
                            <enumeration value="Stem"/>
                        </restriction>
                    </simpleType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== vbarab/webApp/src/main/java/com/epam/vb/entity/Blog/task_Schema/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<Flower  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://myFlowerSchema.kz"
         xsi:schemaLocation="http://myFlowerSchema.kz schema.xsd">
    <Name>Name</Name>
    <Soil>Clay</Soil>
    <Origin>Usa</Origin>
    <VisualParameters>
        <StemColor>green</StemColor>
        <LeafColor>blue</LeafColor>
        <AvarageSize>12</AvarageSize>
    </VisualParameters>
    <GrowingTips>
        <Temperature>12</Temperature>
        <Light>Low</Light>
        <Watering>200</Watering>
    </GrowingTips>
    <Multiplying>Seed</Multiplying>
   </Flower>
